### ISSUE TITLE
change the icons

### ISSUE THREAD

**Issue by surfer77** [rajasegar/ember-responsive-tabs#1]
Hi, how can I chance the icons to add font-awesome icons? , also when I check the tabs on mobile the titles of the tabs disappeared, I can't see the icons either on mobile or on full size screen but I guess on mobile only the icons will appear like the example?
thanks!

**Comment by rajasegar** [comment]
In mobile, you should only get the icons view and the labels disappear
For changing icons, change the font-family of the following to font-awesome

/* Icons */
.tabs nav a:before {
	  font-family: 'font-awesome';
}

Import the fontawesome using @fontface

And override their content like this

.icon-food:before {
	  content: "\e600";
}

.icon-lab:before {
	  content: "\e601";
}

.icon-cup:before {
	  content: "\e602";
}

.icon-truck:before {
	  content: "\e603";
}

.icon-shop:before {
	  content: "\e604";
}

**Comment by surfer77** [comment]
Hi, thanks for the answer but still can't get it to work this is the code I put: in my main css

/assets/styles/font-awesome.min.css");```

@import url("https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,700,900");

.tabs nav a:before {
font-family: 'font-awesome';
}

icon-food:before {
content: "\e600";
}

.icon-lab:before {
content: "\e601";
}

.icon-cup:before {
content: "\e602";
}

.icon-truck:before {
content: "\e603";
}

.icon-shop:before {
content: "\e604";
}

```

I also installed the font awesome ember addon and added the fonts folder and font-awesome min .js manually too.

**Comment by rajasegar** [comment]
Do you have a sample repository so that i can check it
